apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-main-nfs
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: dev-main-nfs
  mountOptions:
  - hard
  - nfsvers=4.1
  - nosuid
  - nodev
  nfs:
    server: 10.0.1.100
    path: /kube-data
