apiVersion: v1
kind: PersistentVolume
metadata:
  name: kube-main-nfs
spec:
  accessModes:
  - ReadWriteMany # ReadOnlyMany, ReadWriteOnce
  capacity:
    storage: 1Ti
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: kube-main-nfs
  mountOptions:
  - hard
  - nfsvers=4.1
  - nosuid
  - nodev
  nfs: # NFS server at 10.0.1.100:/kube-data
    path: /kube-data 
    server: 10.0.1.100