apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: simpleweb
    name: simpleweb
  name: simpleweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simpleweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: simpleweb
        name: simpleweb
    spec:
      volumes:
      - name: nginx-vol
        persistentVolumeClaim:
          claimName: pvc-nginx-data # Must match storageClassName in pv-definition.yaml
      containers:
      - image: nginx
        name: nginx
        resources: {}
        volumeMounts:
        - mountPath: /var/www/html
          name: nginx-vol # Must match the volume name   
status: {}