apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev-gitlab
  name: dev-gitlab-svc
spec:
  ports:
  # Port 1 - expose 443 to the gitlab pod
  - port: 8080 # internal port
    protocol: TCP
    targetPort: 443 # actual port service listens on
    nodePort: 30240 # external port clients will use
  # Port 2 - expose 22 to the gitlab pod
  - port: 8081
    protocol: TCP
    targetPort: 22
    nodePort: 30241
  selector:
    app: dev-gitlab 
  type: NodePort